// Generated by CoffeeScript 1.7.1
var Crawler, FCTNEWS, FILEPATH, articles, converter, extra, fctNewsCrawler, jf, readArticles, requestCreateArticle, sanitize, toMarkdown, user, util, writeArticles;

jf = require('jsonfile');

util = require('util');

converter = require('pagedown').getSanitizingConverter();

extra = require('pagedown-extra').Extra;

extra.init(converter);

sanitize = converter.makeHtml;

requestCreateArticle = require('../helpers/request-create-article');

FILEPATH = 'backups/fctnews.backup';

articles = {};

FCTNEWS = 'http://www.fct.unl.pt/noticias';

writeArticles = function() {
    return jf.writeFile(FILEPATH, articles, function(err) {
        if (err) {
            return console.log(err);
        }
    });
};

user = {
    email: 'fs@gmail.com',
    password: 'gg'
};

Crawler = require('crawler').Crawler;

readArticles = function() {
    return jf.readFile(FILEPATH, function(err, obj) {
        if (err) {
            return console.log(err);
        }
        return articles = obj;
    });
};

fctNewsCrawler = new Crawler({
    maxConnections: 20,
    callback: function(err, result, $) {
        if (err) {
            return console.log(err);
        }
        return $('.views-field-title a').each(function(index, element) {
            return fctNewsCrawler.queue({
                uri: element.href,
                callback: function(err, result, $) {
                    var $images, $nodeContent, articleId, content, sanitizedContent, summary;
                    if (err) {
                        return console.log(err);
                    }
                    articleId = $('div[id^=node-]').attr('id');
                    if (articles[articleId] != null) {
                        return console.log('Article already exists');
                    }
                    $nodeContent = $('.node .content');
                    articles[articleId] = {};
                    articles[articleId].title = $('h1.page-titles').text();
                    if (articles[articleId].title.length > 150) {
                        articles[articleId] = null;
                        return console.log('Title is too long');
                    }
                    articles[articleId].imgPath = 'http://www.fct.unl.pt/sites/default/files/imagens/noticias/noticias.jpg';
                    $images = $nodeContent.find('img');
                    $images.each(function() {
                        return articles[articleId].imgPath = $(this).attr('src');
                    });
                    $images.remove();
                    $nodeContent.find('table,thead,tbody,tfoot,tr,th,td').removeAttr('id').removeAttr('class');
                    content = $nodeContent.html().replace(/[\t\f ]{2,}/g, ' ').replace(/\n /g, '\n').trim();
                    sanitizedContent = sanitize(content);
                    articles[articleId].content = sanitizedContent;
                    if (content && !content.length) {
                        articles[articleId] = null;
                        return console.log('No content');
                    }
                    $nodeContent.find('img').remove();
                    $nodeContent.find('table').remove();
                    $nodeContent.find('div, span').each(function() {
                        var $this;
                        $this = $(this);
                        return $this.contents().unwrap();
                    });
                    summary = '';
                    $nodeContent.find('p').each(function() {
                        return summary += $(this).text().trim() + '\n';
                    });
                    if (!summary.length) {
                        summary = $nodeContent.text().trim();
                    }
                    if (!summary.length) {
                        return console.log('Could not generate brief from content');
                    }
                    summary = summary;
                    if (summary.length > 140) {
                        summary = summary.slice(0, 137).concat('...');
                    }
                    articles[articleId].brief = summary;
                    articles[articleId].tags = [
	            {
                	"authenticated": false,
                	"imgPath": "http://noticias.universia.pt/pt/images/universia/u/un/unl/unl_fct.jpg",
               		"brief": "Notícias da fct",
                	"name": "fct",
                	"id": 1,
                	"parents":[]
	            }];
                    articles[articleId].id = -1;
                    articles[articleId].show = false;
                    articles[articleId].authorId = -1;
                    articles[articleId].likes = 0;
                    articles[articleId].reports = 0;
                    articles[articleId].likeWeight = -1;
                    articles[articleId].reportWeight = -1;
		    articles[articleId].creationDate = null;
		    articles[articleId].eventDate = null;
 			
                    return requestCreateArticle.create(articles, articleId, user, writeArticles);
                }
            });
        });
    }
});

module.exports = {
    user: user,
    crawler: fctNewsCrawler,
    readArticles: readArticles,
    queue: function() {
        return fctNewsCrawler.queue(FCTNEWS);
    }
};
